const {JSDOM}=require('jsdom');
const assert=require('node:assert/strict'),fs=require('fs'),crypto=require('node:crypto');
function app(path){const source=fs.readFileSync(path,'utf8');const dom=new JSDOM(source,{url:'https://aca-test.invalid/',runScripts:'outside-only'});const w=dom.window;w.TextEncoder=TextEncoder;w.TextDecoder=TextDecoder;w.structuredClone=structuredClone;Object.defineProperty(w,'crypto',{value:crypto.webcrypto});w.alert=()=>{};w.confirm=()=>true;w.console={...console,warn:()=>{}};const scripts=[...source.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).join('\n');require('vm').runInContext(scripts,dom.getInternalVMContext());return {w,eval:code=>require('vm').runInContext(code,dom.getInternalVMContext()),close:()=>w.close()};}
(async()=>{
 const a=app('index.html'),doc=a.w.document;const results=[];
 const run=async code=>{const value=await a.eval(code);return value===undefined?null:JSON.parse(JSON.stringify(value));};
 a.eval("  const data=new Map();let denied=false;\n  const doc=(fs,col,id)=>({id,path:col+'/'+id,parent:{id:col}});\n  const snap=ref=>({id:ref.id,ref,exists:()=>data.has(ref.path),data:()=>structuredClone(data.get(ref.path))});\n  const native={fs:{},doc,getDoc:async ref=>snap(ref),setDoc:async(ref,value)=>{if(denied)throw Error('simulated offline');data.set(ref.path,structuredClone(value));},deleteDoc:async ref=>data.delete(ref.path),runTransaction:async(fs,fn)=>{if(denied)throw Error('simulated offline');const writes=[];await fn({get:async ref=>snap(ref),set:(ref,v)=>writes.push([ref.path,structuredClone(v)])});writes.forEach(([k,v])=>data.set(k,v));},collection:(fs,c)=>c,getDocs:async c=>({docs:[...data].filter(([k])=>k.startsWith(c+'/')).map(([k])=>snap(doc({},c,k.split('/')[1])))}),writeBatch:()=>{const writes=[];return {set:(ref,v)=>writes.push(()=>data.set(ref.path,structuredClone(v))),update:(ref,v)=>writes.push(()=>data.set(ref.path,{...data.get(ref.path),...v})),commit:async()=>writes.forEach(f=>f())};}};\n  window.testNative=native;window.testData=data;window.testOffline=v=>denied=v;_db=wrapDB(native);");
 async function test(name,fn){await fn();results.push(name);}
 await test('Login sin contraseñas',async()=>{assert.equal(doc.querySelectorAll('input[type=password]').length,0);assert.ok(doc.querySelector('#google-login'));});
 await test('Parseo decimal numérico y argentino; cero preservado',async()=>{assert.deepEqual(await run("[parseArg(1234.56),parseArg('1.234,56'),parseArg(0),pN('0')]"),[1234.56,1234.56,0,0]);});
 await test('YER inválido no se sanea de manera destructiva',async()=>{assert.equal(await run("sanitizeYER('{\"rows\":\"incorrecto\"}')"),null);});
 await test('YER porcentaje y pesos/litro',async()=>{assert.deepEqual(await run("(()=>{CURRENT_CR='3611';YER.rates={super:{mode:'porcentaje',value:8}};YER.rows=[{combustKey:'super',precio:1200,litros:10,total:12000}];recalcYERRows();const x=YER.rows[0].totalCom;YER.rates.super={mode:'pesos_litro',value:40};recalcYERRows();return [x,YER.rows[0].totalCom];})()"),[960,400]);});
 await test('Recuperos porcentaje, factura, mixto y litros',async()=>{assert.deepEqual(await run("[calculateEconomic({mode:'porcentaje',pct:40,vat:0,deductIVA:true},{base:1210,iva:210}),calculateEconomic({mode:'factura',vat:0},{factura:1500}),calculateEconomic({mode:'mixto',pct:10,vat:0},{base:10000,factura:2000}),calculateEconomic({mode:'litros',litros:80,vat:21},{precio:1000})]"),[400,1500,3000,96800]);});
 await test('Rechazo de deducciones mayores que la base',async()=>{assert.equal(await run("(()=>{try{calculateEconomic({mode:'porcentaje',pct:10,vat:0,deductIVA:true},{base:10,iva:20});return false;}catch{return true;}})()"),true);});
 await test('Archivo grande fragmentado y recuperado íntegro',async()=>{assert.equal(await run("(async()=>{const value='ñ'.repeat(1800000);const ref=testNative.doc({},'kv','cr3611--file--grande');await _db.setDoc(ref,{v:value,k:'cr3611:file:grande',updatedAt:1});return (await _db.getDoc(ref)).data().v===value;})()"),true);});
 await test('Fragmento faltante detectado',async()=>{assert.equal(await run("(async()=>{const m=testData.get('kv/cr3611--file--grande');const k='kv/cr3611--file--grande--chunk--'+m.revision+'--0';const value=testData.get(k);testData.delete(k);try{await _db.getDoc(testNative.doc({},'kv','cr3611--file--grande'));return false;}catch{return true;}finally{testData.set(k,value);}})()"),true);});
 await test('Conflicto de otra sesión conserva su versión',async()=>{assert.equal(await run("(async()=>{const ref=testNative.doc({},'kv','cr3611--data--conflict');testData.set(ref.path,{v:'original'});await _db.getDoc(ref);testData.set(ref.path,{v:'otra sesión'});try{await _db.setDoc(ref,{v:'mi sesión'});return false;}catch(e){return e.code==='aca/conflict'&&testData.get(ref.path).v==='otra sesión';}})()"),true);});
 await test('Cola con versión base sincroniza después de recargar',async()=>{assert.deepEqual(await run(`(async()=>{CURRENT_CR='3531';_cache={};_syncQueue={};_syncErrors={};_syncInit=true;const fk=fullKey('data:2040-02'),id=encodeKey(fk),path='kv/'+id;testData.set(path,{v:'nube',k:fk,updatedAt:1});_db=wrapDB(testNative);await sGet('data:2040-02');testOffline(true);const first=await sSet('data:2040-02','local');testOffline(false);const queued=syncEntry(_syncQueue[fk]);_db=wrapDB(testNative);const synced=await sincronizar(false);return [first,queued.legacy,synced,syncPend(),testData.get(path).v];})()`),[false,false,true,0,'local']);});
 await test('Cola anterior queda pendiente y no pisa la nube',async()=>{assert.deepEqual(await run(`(async()=>{CURRENT_CR='3531';_cache={};_syncQueue={};_syncErrors={};_syncInit=true;const fk=fullKey('data:2040-03'),path='kv/'+encodeKey(fk);testData.set(path,{v:'nube',k:fk,updatedAt:1});_syncQueue[fk]='cambio versión anterior';_db=wrapDB(testNative);const synced=await sincronizar(false);return [synced,syncPend(),testData.get(path).v,_syncErrors[fk].code];})()`),[false,1,'nube','aca/legacy-queue']);});
 await test('Descartar pendientes antiguos no toca Firebase ni cambios nuevos',async()=>{assert.deepEqual(await run(`(()=>{CURRENT_CR='3531';_cache={};_syncErrors={};const oldA=fullKey('data:2040-05'),oldB=fullKey('file:full:2040-05'),fresh=fullKey('data:2040-06'),remote='kv/'+encodeKey(oldA);testData.set(remote,{v:'nube intacta',k:oldA});_syncQueue={[oldA]:'local antiguo',[oldB]:{schema:1,value:'archivo antiguo'},[fresh]:{schema:2,value:'local nuevo',base:null}};_cache={[oldA]:'local antiguo',[oldB]:'archivo antiguo',[fresh]:'local nuevo'};lsSet(oldA,'local antiguo');lsSet(oldB,'archivo antiguo');lsSet(fresh,'local nuevo');const removed=clearLegacyPendingLocal();return [removed,Object.keys(_syncQueue).length,_syncQueue[fresh].value,_cache[fresh],lsGet(oldA),lsGet(oldB),lsGet(fresh),testData.get(remote).v];})()`),[2,1,'local nuevo','local nuevo',null,null,'local nuevo','nube intacta']);});
 await test('Orden distinto de campos no genera un falso conflicto',async()=>{assert.deepEqual(await run(`(async()=>{CURRENT_CR='3531';_cache={};_syncErrors={};_syncInit=true;const fk=fullKey('data:2040-07'),path='kv/'+encodeKey(fk);testData.set(path,{updatedAt:1,k:fk,v:'nube'});_syncQueue={[fk]:{schema:2,value:'local',base:JSON.stringify({v:'nube',k:fk,updatedAt:1})}};_db=wrapDB(testNative);const synced=await sincronizar(false);return [synced,syncPend(),testData.get(path).v];})()`),[true,0,'local']);});
 await test('Resolver conflicto respalda la nube y guarda la versión local',async()=>{assert.deepEqual(await run(`(async()=>{CURRENT_CR='3531';_cache={};_syncErrors={};_syncInit=true;const fk=fullKey('data:2040-08'),path='kv/'+encodeKey(fk);testData.set(path,{v:'original',k:fk,updatedAt:1});_db=wrapDB(testNative);const base=await _db.ensureExpected(testNative.doc({},'kv',encodeKey(fk)));_syncQueue={[fk]:{schema:2,value:'local',base}};testData.set(path,{v:'otra sesión',k:fk,updatedAt:2});await sincronizar(false);const resolved=await resolvePendingConflicts();const backup=[...testData].find(([k,v])=>k.includes('--backup--')&&v.backupOf===encodeKey(fk));return [resolved,syncPend(),testData.get(path).v,backup?.[1]?.v];})()`),[true,0,'local','otra sesión']);});
 await test('Cola nueva detecta cambio remoto y conserva ambas versiones',async()=>{assert.deepEqual(await run(`(async()=>{CURRENT_CR='3531';_cache={};_syncQueue={};_syncErrors={};_syncInit=true;const fk=fullKey('data:2040-04'),id=encodeKey(fk),path='kv/'+id;testData.set(path,{v:'original',k:fk,updatedAt:1});_db=wrapDB(testNative);await sGet('data:2040-04');testOffline(true);await sSet('data:2040-04','local');testOffline(false);testData.set(path,{v:'otra sesión',k:fk,updatedAt:2});_db=wrapDB(testNative);const synced=await sincronizar(false);return [synced,syncPend(),testData.get(path).v,_syncErrors[fk].code];})()`),[false,1,'otra sesión','aca/conflict']);});
 await test('Respaldo anterior a modificar documento',async()=>{assert.equal(await run("(async()=>{const ref=testNative.doc({},'kv','cr3611--data--backup');await _db.setDoc(ref,{v:'viejo'});await _db.setDoc(ref,{v:'nuevo'});return [...testData].some(([k,v])=>k.includes('--backup--')&&v.v==='viejo');})()"),true);});
 await test('Borrado físico deshabilitado',async()=>{assert.equal(await run("(async()=>{try{await _db.deleteDoc(testNative.doc({},'kv','algo'));return false;}catch{return true;}})()"),true);});
 await test('Solicitud pendiente no abre datos de estación',async()=>{await run("(async()=>{AUTH_PERSON={uid:'usuario-prueba',email:'prueba@example.com',emailVerified:true};await resolveAccess();})()");doc.querySelector('#request-cr').value='3611';doc.querySelector('#request-access').dispatchEvent(new a.w.Event('submit',{cancelable:true}));await new Promise(r=>setTimeout(r,30));assert.match(doc.querySelector('#app').textContent,/pendiente de autorización/);assert.equal(await run('CU'),null);});
 await test('Administrador aprueba Gmail y CR solicitados',async()=>{await run("(async()=>{testData.set('admins/admin-prueba',{enabled:true});AUTH_PERSON={uid:'admin-prueba',email:'admin@example.com',emailVerified:true};await resolveAccess();})()");await new Promise(r=>setTimeout(r,30));doc.querySelector('[data-approve]').click();await new Promise(r=>setTimeout(r,30));assert.equal(await run("testData.get('access/usuario-prueba').cr"),'3611');assert.equal(await run("testData.get('access/usuario-prueba').enabled"),true);});
 await test('Revocar cuenta no elimina documentos',async()=>{const n=await run('testData.size');doc.querySelector('[data-toggle]').click();await new Promise(r=>setTimeout(r,30));assert.equal(await run("testData.get('access/usuario-prueba').enabled"),false);assert.equal(await run('testData.size'),n);});
 await test('Full 10% y 12%, siempre sin cigarrillos',async()=>{assert.deepEqual(await run("(()=>{CURRENT_CR='3531';ECON=[];const legacy=fullBase(10000,2000)*fullRate();CURRENT_CR='3611';ECON=[{cr:'3611',vigencia:'2020-01',full:{enabled:true,pct:10}}];return [legacy,fullBase(10000,2000)*fullRate()];})()"),[960,800]);});
 await test('Full recupera comprobantes con claves históricas sin migrarlos',async()=>{assert.deepEqual(await run(`(async()=>{const old=sGet;try{const files=new Map([['file:2026-06:full.comprobanteTransferencia','pdf histórico']]);sGet=async key=>files.get(key)||null;const found=await readFullFile('2026-05','comprobanteTransferencia');return [found.key,found.raw,fullFileKey('2026-05','comprobanteTransferencia'),fullFileCandidates('2026-05','comprobanteTransferencia')];}finally{sGet=old;}})()`),['file:2026-06:full.comprobanteTransferencia','pdf histórico','file:full:2026-05:comprobanteTransferencia',['file:full:2026-05:comprobanteTransferencia','file:full:comp:2026-05','file:2026-06:full.comprobanteTransferencia','file:2026-05:full.comprobanteTransferencia']]);});
 await test('Full prioriza la clave registrada del adjunto',async()=>{assert.deepEqual(await run(`(async()=>{const old=sGet;try{const files=new Map([['file:full:2026-08:comprobanteTransferencia','canónico'],['file:clave-registrada','registrado']]);sGet=async key=>files.get(key)||null;const found=await readFullFile('2026-08','comprobanteTransferencia','file:clave-registrada');return [found.key,found.raw];}finally{sGet=old;}})()`),['file:clave-registrada','registrado']);});
 await test('Checks: números repetidos no cierran otra auditoría',async()=>{assert.deepEqual(await run(`(()=>{const raw=JSON.stringify([{items:[{n:1,cerrada:false}]},{items:[{n:1,cerrada:false}]}]);const r=findAndUpdateNC(raw,1,x=>x.cerrada=true,1);const out=JSON.parse(r.updated);return [out[0].items[0].cerrada,out[1].items[0].cerrada,findAndUpdateNC(raw,1,x=>x.cerrada=true).found];})()`),[false,true,false]);});
 await test('Fallo de lectura sin respaldo bloquea carga',async()=>{assert.equal(await run(`(async()=>{const old=_db.getDoc;_db.getDoc=async()=>{throw Error('offline');};try{await sGet('data:2040-01');return false;}catch{return true;}finally{_db.getDoc=old;}})()`),true);});
 await test('Cambio de vigencia no altera registro ya calculado',async()=>{assert.equal(await run(`(()=>{const condition={mode:'porcentaje',pct:10,vat:0};const record={condition:structuredClone(condition),total:calculateEconomic(condition,{base:1000})};condition.pct=20;return record.total===100&&record.condition.pct===10;})()`),true);});

 await test('Hotel factura menos NC reproduce agosto de Cipolletti',async()=>{assert.equal(await run("calculateEconomic({area:'hotel',mode:'factura',vat:0},{factura:20144628.75,notaCredito:4028925.76})"),16115702.99);});
 await test('Hotel mixto y porcentaje descuentan NC y rechazan exceso',async()=>{assert.deepEqual(await run("[calculateEconomic({area:'hotel',mode:'mixto',pct:10,vat:0},{base:10000,factura:2000,notaCredito:500}),calculateEconomic({area:'hotel',mode:'porcentaje',pct:10,vat:0},{base:10000,notaCredito:100})]"),[2500,900]);assert.equal(await run("(()=>{try{calculateEconomic({area:'hotel',mode:'factura',vat:0},{factura:100,notaCredito:101});return false;}catch{return true;}})()"),true);});
 await test('Hotel guarda factura y NC separadas; valida referencia y conserva adjunto',async()=>{
 a.eval("CURRENT_CR='3531';CP='2026-10';CU={username:'test@example.com'};ECON=[{cr:CURRENT_CR,vigencia:CP,concepts:[{id:'hotel',name:'Hotel',area:'hotel',enabled:true,mode:'factura',vat:0}]}];window.entryMemory=new Map();sGet=async k=>entryMemory.get(k)||null;sSet=async(k,v)=>{entryMemory.set(k,v);return true;};readDU=async()=> 'data:application/pdf;base64,JVBERg==';");
 if(!doc.getElementById("tab-content")){const el=doc.createElement("div");el.id="tab-content";doc.body.appendChild(el);}await run("renderEconomicEntry('hotel')");let form=doc.querySelector('[data-entry]');const fill=(k,v)=>{form.querySelector('[data-k="'+k+'"]').value=v;};fill('factura','1000');fill('notaCredito','200');fill('nro','F-1');fill('fecha','2026-10-01');await form.onsubmit({preventDefault(){}});assert.match(form.querySelector('output').textContent,/número y fecha/);assert.equal(await run('entryMemory.size'),0);
 fill('ncNro','NC-1');fill('ncFecha','2026-10-02');form.querySelector('.ee-file').onchange({target:{files:[{name:'factura.pdf',type:'application/octet-stream',size:4}]}});form.querySelector('.ee-nc-file').onchange({target:{files:[{name:'nota.pdf',type:'application/pdf',size:4}]}});await form.onsubmit({preventDefault(){}});
 assert.deepEqual(await run("(()=>{const e=JSON.parse(entryMemory.get('economic:entries:'+CP))[0];return [e.total,e.values.ncNro,JSON.parse(entryMemory.get(e.fileKey)).fileName,JSON.parse(entryMemory.get(e.ncFileKey)).fileName];})()"),[800,'NC-1','factura.pdf','nota.pdf']);assert.ok(doc.querySelector('[data-ee-nc-view]'));
 });
 await test('Recupero importe total menos IVA menos percepciones',async()=>{assert.equal(await run("calculateEconomic({mode:'total_menos_iva_percepciones',vat:21},{base:1210,iva:210,percepciones:10})"),990);assert.equal(await run("(()=>{try{calculateEconomic({mode:'total_menos_iva_percepciones',vat:0},{base:100,iva:80,percepciones:30});return false;}catch{return true;}})()"),true);});
 const f=app('formulario-condiciones.html');
 await test('Formulario cuatro modalidades YER y recupero adicional',async()=>{assert.equal(f.w.document.querySelectorAll('[data-rate]').length,4);f.w.document.querySelector('#ec-add').click();assert.equal(f.w.document.querySelectorAll('[data-concept]').length,6);});
 await test('Formulario incompleto no se acepta',async()=>{f.w.document.querySelector('#ec-form').dispatchEvent(new f.w.Event('submit',{cancelable:true}));assert.match(f.w.document.querySelector('#ec-status').textContent,/vigencia/);});
 await test('Formulario completo exporta valores por producto y medidor',async()=>{f.eval(`econDownload=(name,value)=>{window.exported=value;};`);const d=f.w.document;const fill=(el,key,value)=>{el.querySelector('[data-k="'+key+'"]').value=value;};const h=d.querySelector('#ec-head');fill(h,'vigencia','2026-10');fill(h,'responsable','Persona de prueba');fill(h,'email','persona@example.com');fill(d.querySelector('#ec-full'),'pct','10');d.querySelectorAll('[data-rate]').forEach(x=>fill(x,'value','5'));fill(d.querySelector('[data-rate="super"]'),'mode','pesos_litro');fill(d.querySelector('[data-rate="super"]'),'value','45');d.querySelectorAll('[data-concept]').forEach((x,i)=>{fill(x,'name','Concepto '+i);fill(x,'base','Base de prueba');fill(x,'pct','100');fill(x,'litros','80');});d.querySelector('#ec-form').dispatchEvent(new f.w.Event('submit',{cancelable:true}));assert.equal(f.w.exported.yer.super.mode,'pesos_litro');assert.equal(f.w.exported.yer.super.value,45);assert.equal(f.w.exported.full.excludeCigarettes,true);assert.equal(f.w.exported.concepts.length,6);});
 fs.writeFileSync('pruebas.json',JSON.stringify({passed:results.length,tests:results,scope:'Pruebas de funciones y DOM en Node/jsdom con base simulada. Sin Google real, sin Firestore ni emulador de reglas; no es revisión visual.'},null,2));console.log(JSON.stringify({passed:results.length,tests:results},null,2));a.close();f.close();
})().catch(e=>{console.error(e);process.exit(1)});
